import { useState } from "react";
import { ArrowRight, Disc3, Headphones, Home, Library, LogOut, Search, Settings, Sparkles, Upload } from "lucide-react";
import Logo from "../ui/Logo";

function DashboardSidebar({ artist, active, setActive, onExit, onLogout }) {
  const items = artist
    ? [{ name: "My library", icon: Library }, { name: "Upload music", icon: Upload }, { name: "Create album", icon: Disc3 }, { name: "All songs", icon: Headphones }]
    : [{ name: "Home", icon: Home }, { name: "Discover", icon: Sparkles }, { name: "All albums", icon: Disc3 }, { name: "Your library", icon: Library }];

  return <aside className="sticky top-0 hidden h-screen w-64 shrink-0 flex-col overflow-y-auto border-r border-line bg-paper px-5 py-7 lg:flex"><Logo onClick={onExit} /><nav className="mt-14 space-y-1">{items.map(({ name, icon: Icon }) => <button key={name} onClick={() => setActive(name)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold transition-colors ${active === name ? "bg-lime text-ink" : "text-sage hover:bg-cream hover:text-ink"}`}><Icon size={18} />{name}</button>)}</nav><div className="mt-auto rounded-2xl bg-ink p-4 text-paper"><p className="text-sm font-semibold">{artist ? "Keep creating" : "Find something new"}</p><p className="mt-1 text-xs leading-5 text-paper/60">{artist ? "Share your next track with listeners." : "A fresh selection is waiting."}</p><button onClick={() => setActive(artist ? "Upload music" : "Discover")} className="mt-4 flex items-center gap-1 text-xs font-semibold text-lime">{artist ? "Upload music" : "Explore picks"} <ArrowRight size={13} /></button></div><button onClick={onLogout} className="mt-5 flex items-center gap-3 px-3 py-2 text-sm text-sage hover:text-ink"><LogOut size={16} /> Log out</button></aside>;
}

export default function DashboardFrame({ children, artist, active, setActive, onExit, onLogout, onSearch }) {
  const [searchOpen, setSearchOpen] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);
  return <div className="flex min-h-screen bg-cream"><DashboardSidebar artist={artist} active={active} setActive={setActive} onExit={onExit} onLogout={onLogout} /><div className="flex min-w-0 flex-1 flex-col"><header className="relative flex min-h-[76px] items-center justify-between border-b border-line bg-cream/90 px-5 py-3 sm:px-8 lg:px-10"><div className="lg:hidden"><Logo onClick={onExit} /></div><div className="ml-auto flex items-center gap-2"><button onClick={() => setSearchOpen(!searchOpen)} className="rounded-full p-2 text-sage hover:bg-paper" aria-label="Search"><Search size={19} /></button><button onClick={() => setSettingsOpen(!settingsOpen)} className="rounded-full p-2 text-sage hover:bg-paper" aria-label="Settings"><Settings size={19} /></button><span className="ml-2 grid h-9 w-9 place-items-center rounded-full bg-[#d8b198] text-sm font-semibold">AM</span></div>{searchOpen && <div className="absolute right-5 top-[68px] z-40 w-[min(90vw,360px)] rounded-xl border border-line bg-paper p-3 shadow-xl sm:right-8"><input autoFocus onChange={(event) => onSearch?.(event.target.value)} placeholder={artist ? "Search songs…" : "Search tracks and artists…"} className="h-10 w-full rounded-lg border border-line bg-cream px-3 text-sm outline-none focus:border-moss" /></div>}{settingsOpen && <div className="absolute right-5 top-[68px] z-40 w-56 rounded-xl border border-line bg-paper p-3 shadow-xl sm:right-8"><p className="px-2 pb-2 text-xs font-bold uppercase tracking-[.14em] text-sage">Account</p><button onClick={onLogout} className="flex w-full items-center gap-2 rounded-lg px-2 py-2 text-sm text-sage hover:bg-cream hover:text-ink"><LogOut size={16} /> Log out</button></div>}</header><main className="flex-1 px-5 py-8 pb-28 sm:px-8 lg:px-10 lg:pb-8">{children}</main><nav className="fixed bottom-0 left-0 right-0 z-30 grid grid-cols-4 border-t border-line bg-paper/95 px-3 py-2 backdrop-blur lg:hidden">{(artist ? [{ name: "My library", icon: Library }, { name: "Upload music", icon: Upload }, { name: "Create album", icon: Disc3 }, { name: "All songs", icon: Headphones }] : [{ name: "Home", icon: Home }, { name: "Discover", icon: Sparkles }, { name: "All albums", icon: Disc3 }, { name: "Your library", icon: Library }]).map(({ name, icon: Icon }) => <button key={name} onClick={() => setActive(name)} className={`flex flex-col items-center gap-1 rounded-lg py-1 text-[10px] font-semibold ${active === name ? "text-ink" : "text-sage"}`}><Icon size={18} />{name}</button>)}</nav></div></div>;
}
